#! /usr/bin/env sh
rm debian/source/include-binaries
./apt-now
for p in $(find -name *.tar.*); do
        echo $p | sed 's|./||'  | tee -a debian/source/include-binaries
done
for p in $(find -name *.deb); do
        echo $p | sed 's|./||'  | tee -a debian/source/include-binaries
done

debuild -us -uc
