Document: apt-now
Title: Debian apt-now Manual
Author: <insert document author here>
Abstract: This manual describes what apt-now is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/apt-now/apt-now.sgml.gz

Format: postscript
Files: /usr/share/doc/apt-now/apt-now.ps.gz

Format: text
Files: /usr/share/doc/apt-now/apt-now.text.gz

Format: HTML
Index: /usr/share/doc/apt-now/html/index.html
Files: /usr/share/doc/apt-now/html/*.html
